"""Maya4 - SAR data loading and processing utilities."""

__version__ = "0.1.2"
__author__ = "Roberto Del Prete"

from .api import (
    DEFAULT_BUCKET_ID,
    download_file_from_bucket,
    download_file_from_hf,
    download_metadata_from_product,
    fetch_chunk_from_bucket_zarr,
    fetch_chunk_from_hf_zarr,
    filter_files_by_modalities,
    list_base_files_in_bucket,
    list_base_files_in_repo,
    list_files_in_bucket,
    list_files_in_repo,
    list_repos_by_author,
)
from .dataloader import (
    KPatchSampler,
    LazyCoordinateGenerator,
    LazyCoordinateRange,
    SARDataloader,
    SARZarrDataset,
    get_sar_dataloader,
)
from .location_utils import (
    extract_location_from_zarr_filename_with_phidown,
    get_location_for_zarr_file,
    get_products_spatial_mapping,
    get_sar_product_locations,
)
from .normalization import (
    AdaptiveNormalizationModule,
    AdaptiveZScoreNormalize,
    BaseTransformModule,
    ComplexNormalizationModule,
    IdentityModule,
    NormalizationModule,
    RobustNormalize,
    SARTransform,
    ZScoreNormalize,
)
from .utils import (
    GT_MAX,
    GT_MIN,
    LOCATIONS_CSV_FILENAME,
    RC_MAX,
    RC_MIN,
    SampleFilter,
    build_local_product_path,
    create_dataloader_from_config,
    create_dataloaders,
    create_transforms_from_config,
    display_inference_results,
    extract_stripmap_mode_from_filename,
    get_balanced_sample_files,
    get_chunk_name_from_coords,
    get_part_from_filename,
    get_sample_visualization,
    get_zarr_version,
    minmax_inverse,
    minmax_normalize,
    parse_product_filename,
)

try:
    from .dataset_creation import dask_slice_saver, save_array_to_zarr
except ImportError:  # optional dependency: dask
    dask_slice_saver = None
    save_array_to_zarr = None

__all__ = [
    "AdaptiveNormalizationModule",
    "AdaptiveZScoreNormalize",
    "BaseTransformModule",
    "ComplexNormalizationModule",
    "DEFAULT_BUCKET_ID",
    "GT_MAX",
    "GT_MIN",
    "IdentityModule",
    "KPatchSampler",
    "LOCATIONS_CSV_FILENAME",
    "LazyCoordinateGenerator",
    "LazyCoordinateRange",
    "NormalizationModule",
    "RC_MAX",
    "RC_MIN",
    "RobustNormalize",
    "SARDataloader",
    "SARTransform",
    "SARZarrDataset",
    "SampleFilter",
    "ZScoreNormalize",
    "build_local_product_path",
    "create_dataloader_from_config",
    "create_dataloaders",
    "create_transforms_from_config",
    "dask_slice_saver",
    "display_inference_results",
    "download_file_from_bucket",
    "download_file_from_hf",
    "download_metadata_from_product",
    "extract_location_from_zarr_filename_with_phidown",
    "extract_stripmap_mode_from_filename",
    "fetch_chunk_from_bucket_zarr",
    "fetch_chunk_from_hf_zarr",
    "filter_files_by_modalities",
    "get_balanced_sample_files",
    "get_chunk_name_from_coords",
    "get_location_for_zarr_file",
    "get_part_from_filename",
    "get_products_spatial_mapping",
    "get_sample_visualization",
    "get_sar_dataloader",
    "get_sar_product_locations",
    "get_zarr_version",
    "list_base_files_in_bucket",
    "list_base_files_in_repo",
    "list_files_in_bucket",
    "list_files_in_repo",
    "list_repos_by_author",
    "minmax_inverse",
    "minmax_normalize",
    "parse_product_filename",
    "save_array_to_zarr",
]
